version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: "blitz-world_nginx_1"
      APP_PORT: 80

  nginx:
    image: nginx:latest

  agent:
    image: skisel/blitz-agent:5
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/data/app:/data"
      - "${APP_LIGHTNING_NODE_DATA_DIR}/tls.cert:/lnd/tls.cert:ro"
      - "${APP_LIGHTNING_NODE_DATA_DIR}/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/readonly.macaroon:/lnd/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/readonly.macaroon:ro"
    environment:
      LND_CERT_FILE: "/lnd/tls.cert"
      LND_MACAROON_FILE: "/lnd/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/readonly.macaroon"
      LND_HOST: "${APP_LIGHTNING_NODE_IP}"
      LND_PORT: "${APP_LIGHTNING_NODE_GRPC_PORT}"
      AUTHENTICATOR_SERVICE_ACCOUNT_PATH: "/data/service-account.json"
