version: "3.7"

services:

  agent:
    image: britva/blitz-agent:4
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/root/.lnd:ro
    environment:
      SERVER_URL: https://9c20-2001-1620-537d-0-f5ed-3a9d-90bc-8789.ngrok-free.app
